# Week 7, Monday Lecture

The focus on this week will be on NumPy. We have already seen this library during Week 6, but let us know if you are having any trouble getting it installed.

__Reminders:__

 - No lecture on Friday, November 11th. 
 - Python Homework #2 will be assigned during Wednesday this week. It will be due Friday of Week 8, so you have a little extra time to work on it.
 
__Today:__
 
 - Creating regular arrays in NumPy
 - Random numbers in NumPy
 
 ***

In [1]:
import numpy as np

## Regular Arrays

What do we mean by regular? We mean that the arrays follow some kind of pattern.

How could we make the following NumPy arrays?

 - `[0,0,...]` total length 13

In [2]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(13).shape

(13,)

In [5]:
np.zeros(13, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr = np.zeros(13, dtype=np.int8)

In [9]:
type(arr)

numpy.ndarray

In [10]:
[0 for _ in range(13)] #list comprehension

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [12]:
np.array([x for x in range(13)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
[0]+[0]

[0, 0]

In [14]:
[0] + [0] + [0]

[0, 0, 0]

In [17]:
[0]*13

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

 - A $3 \times 5$ array of all 7's

In [23]:
np.zeros((3,5), int)+7 #shape needs to be a tuple

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [27]:
np.ones((3,5),int)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [26]:
np.array([7]).shape

(1,)

In [20]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

 - An array of the form `[0,...,50]` of 6 evenly spaced points.

In [28]:
np.linspace(0,50,6)

array([ 0., 10., 20., 30., 40., 50.])

We probably won't ever use linspace again for this class, but I just wanted you to see how many MATLAB functions are available in NumPy.

 - The $4 \times 4$ array 
 $$
 \begin{pmatrix}
 0 & 0 & 0 & 0 \\
 1 & 1 & 1 & 1 \\
 2 & 2 & 2 & 2 \\
 3 & 3 & 3 & 3
 \end{pmatrix}
 $$

Let's first practice with some indexing before we try making this array with a for-loop...

In [48]:
A = np.zeros((4,4),int) #Initializing A to be all zeros
for x in range(4):
    A[x] = x

In [49]:
A

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [36]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
#Some special indexing notation! 
A[0] #Returns the entire 0th row!

array([0, 1, 2, 3])

In [38]:
A[1]

array([4, 5, 6, 7])

In [39]:
A[2]

array([ 8,  9, 10, 11])

In [41]:
A[-1]

array([12, 13, 14, 15])

In [42]:
A[3]

array([12, 13, 14, 15])

What if I wanted to get an entire column instead?

In [43]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
A[:,0]

array([ 0,  4,  8, 12])

In [30]:
np.arange(16) #notice how similar this is to regular range(16)!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.arange(16).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [34]:
np.arange(16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [35]:
np.arange(16).reshape(3,5)

ValueError: cannot reshape array of size 16 into shape (3,5)

In [31]:
list(range(16))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

 - The $2 \times 5$ array 
 $$
 \begin{pmatrix}
 1 & 3 & 5 & 7 & 9 \\
 11 & 13 & 15 & 17 & 19
 \end{pmatrix}
 $$

In [56]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [58]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [57]:
np.arange(1,19,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [54]:
range(1,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [55]:
np.arange(1,10,0.5) #Here is one difference using arange! Non-integer step size! 

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

***

## Random Numbers!
... and a small introduction to object-oriented programming.

 - Instantiate a random number generator in NumPy

In [2]:
rng = np.random.default_rng()

In [60]:
type(rng)

numpy.random._generator.Generator

In [61]:
rng.random()

0.6046805857649832

__We didn't get to the material below during the lecture, but here are some ways you could solve the problems__

 - Make a length 13 array of random integers between 3 (inclusive) and 29 (exclusive).

In [4]:
arr = rng.integers(3,29,13)

 - Choose 10 of the numbers from the above array (with replacement) and put them into a new array.

In [6]:
rng.choice(arr,10)

array([ 7, 20, 25,  7, 15, 25, 25, 10, 25, 25])

 - Make a $3 \times 5$ array of random real numbers between -13 and 24.

In [17]:
A = 37*rng.random((3,5))-13
A

array([[ -2.8555958 ,  13.32105895,   3.63612778,   5.60456427,
         -9.80554954],
       [ 18.59932655,   1.46690425,  16.54406516,  23.41668976,
         -0.53462257],
       [-11.11370642,   1.14085123,  12.17964957,  22.914088  ,
        -12.94760729]])

In [18]:
A.max()

23.416689759475332

In [19]:
A.min()

-12.947607292937295

In [20]:
A.shape

(3, 5)